# coding: UTF-8

levels = Level.create([
  { id: 1, sequence: 1, name: 'Apertura', tag: 'aper' },
  { id: 2, sequence: 2, name: 'Problematización', tag: 'prob' },
  { id: 3, sequence: 3, name: 'Información', tag: 'info' },
  { id: 4, sequence: 4, name: 'Aplicación', tag: 'aplic' },
  { id: 5, sequence: 5, name: 'Cierre', tag: 'cierr' },
  ])

quizes = Quiz.create([
  { level_id: 1, sequence: 1,
    question: 'Opine que le pareció el título de la Unidad.', 
    instant_feedback: '' },
  { level_id: 2, sequence: 2, 
    question: '¿Porqué Isabel toma esta decisión en el acto 1?', 
    instant_feedback: '' },
  { level_id: 2, sequence: 3,
    question: '¿Porqué Isabel toma esta decisión en el acto 3?', 
    instant_feedback: '' },
  { level_id: 2, sequence: 4,
    question: 'Comparando ambas respuestas. ¿Cuál es el cambio interno que experimenta Isabel?', 
    instant_feedback: '' },
  { level_id: 2, sequence: 5,
    question: 'Desarrolle un acto 2 escrito en primera persona (como si usted fuera Isabel) que haga coherente su proceso de cambio', 
    instant_feedback: '' },
  { level_id: 3, sequence: 6,
    question: 'En términos generales ¿Qué concluye sobre los cambios generacionales que se han producido en torno a la sexualidad y afectividad?', 
    instant_feedback: '' },
  { level_id: 3, sequence: 7,
    question: '¿Qué puede decir sobre las fuentes con que las personas nos informamos sobre fenómenos relacionados a la sexualidad y afectividad?', 
    instant_feedback: '' },
  { level_id: 3, sequence: 8,
    question: '¿En qué consiste el concepto de Sexualidad Protegida?', 
    instant_feedback: '' },
  { level_id: 3, sequence: 9,
    question: '¿Cuál es su opinión sobre la abstinencia como objetivo para la educación sexual?', 
    instant_feedback: '' },
  { level_id: 3, sequence: 10,
    question: '¿Qué elementos del momento informativo le han sido útiles para comprender mejor a Isabel?', 
    instant_feedback: '' },
  { level_id: 4, sequence: 11,
    question: '¿Porqué Isabel toma esta decisión en el acto 1?', 
    instant_feedback: '' },
  { level_id: 4, sequence: 12,
    question: '¿Porqué Isabel toma esta decisión en el acto 3?', 
    instant_feedback: '' },
  { level_id: 4, sequence: 13,
    question: 'Comparando ambas respuestas ¿Cuál es el cambio interno que experimenta Isabel?', 
    instant_feedback: '' },
  { level_id: 4, sequence: 14,
    question: 'Desarrolle un acto 2 escrito en primera persona (como si usted fuera Isabel) que haga coherente su proceso de cambio', 
    instant_feedback: '' },
  { level_id: 5, sequence: 15,
    question: 'Comparando su primera y segunda resolución del Caso de Aprendizaje. ¿Qué aprendizajes personales identifica?', 
    instant_feedback: '' },
  { level_id: 5, sequence: 16,
    question: 'Comente libremente como evalúa la experiencia de haber realizado este curso.', 
    instant_feedback: '' }
  ])
  
topics = Topic.create([
  { name: "Cafetería", abstract: "En este foro puede conversar lo que desee." },
  { name: "Sexualidad", abstract: "Este foro es para conversar sobre sexualidad." },
  { name: "Soporte Técnico", abstract: "¿Problemas con el curso? Consulte aquí y buscaremos una solución." }
  ])  
